### ISSUE TITLE
生成后的代码里面有*storage.Query, 这个不知道是用了哪个模块，示例代码里面没有的

### ISSUE THREAD

**Issue by bingochen87** [yakumioto/mgen#1]
`func FindUsersByFormQuery(fields *storage.Query) ([]*Users, error) {
	s, c := GetSessionAndCollection(CollectionUsers)
	defer s.Close()

	query := c.Find(fields.Search)

	if len(fields.Sort) != 0 {
		query.Sort(fields.Sort...)
	}

	users := make([]*Users, 0)

	return users, query.Skip(fields.Skip + (fields.Page * fields.Limt)).
		Limit(fields.Limt).
		All(&users)
}`

**Comment by yakumioto** [comment]
emmm..., 你这样一问我自己都有点懵.. 代码太久远了. 建议你当作参考自己写一套, 毕竟每个公司和每个公司的代码风格不太一样.
